# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('recommend', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, choices=[('国内', '国内'), ('国际', '国际'), ('社会', '社会'), ('体育', '体育'), ('财经', '财经'), ('军事', '军事'), ('科技', '科技'), ('搞笑', '搞笑')], max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='banner_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('recommend', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, choices=[('国内', '国内'), ('国际', '国际'), ('社会', '社会'), ('体育', '体育'), ('财经', '财经'), ('军事', '军事'), ('科技', '科技'), ('搞笑', '搞笑')], max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('time', models.DateField(auto_now=True)),
                ('best_comment', models.BooleanField(default=False)),
                ('like_count', models.ImageField(blank=True, null=True, upload_to='')),
                ('belong_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_comments', to='newsApp.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_content', models.CharField(blank=True, max_length=1000, null=True)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hot_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('recommend', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, choices=[('国内', '国内'), ('国际', '国际'), ('社会', '社会'), ('体育', '体育'), ('财经', '财经'), ('军事', '军事'), ('科技', '科技'), ('搞笑', '搞笑')], max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=300, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('recommend', models.BooleanField(default=False)),
                ('tag', models.CharField(blank=True, choices=[('国内', '国内'), ('国际', '国际'), ('社会', '社会'), ('体育', '体育'), ('财经', '财经'), ('军事', '军事'), ('科技', '科技'), ('搞笑', '搞笑')], max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='')),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('dislike', 'dislike'), ('like', 'like'), ('normal', 'normal')], max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tickets', to='newsApp.Article')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('article_id', models.CharField(blank=True, max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('last_time', models.IntegerField(blank=True, default=0, null=True)),
                ('times', models.IntegerField(default=0)),
                ('like_keywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=14, null=True)),
                ('birth', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(upload_to='avatar')),
                ('sex', models.CharField(blank=True, choices=[('男', '男'), ('女', '女')], default=None, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('desc', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('school', models.CharField(blank=True, max_length=50, null=True)),
                ('vocation', models.CharField(blank=True, max_length=50, null=True)),
                ('china', models.BooleanField(default=False)),
                ('world', models.BooleanField(default=False)),
                ('social', models.BooleanField(default=False)),
                ('mil', models.BooleanField(default=False)),
                ('sport', models.BooleanField(default=False)),
                ('tech', models.BooleanField(default=False)),
                ('economic', models.BooleanField(default=False)),
                ('funny', models.BooleanField(default=False)),
                ('background_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('belong_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_username', to='newsApp.UserProfile'),
        ),
    ]
